### ISSUE TITLE
Customizing css for production environment

### ISSUE THREAD

**Issue by nukeop** [arwesjs/arwes#7]
### Subject of the issue
I'm including arwes in my project, and it works great in development environment. I'd like to customize some css, so I added a couple of rules like:

```css
div[class*='ArwesSounds(Footer)-children'] {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

While it works in development environment, in production these class names are replaced by c0124 and other similar names. What can I do to customize the css in production? Or to prevent arwes from changing class names?

### Your environment
Occurs regardless of environment.

### Steps to reproduce
Bundle arwes via webpack and use` mode: 'production'`.

### Expected behaviour
N/A

### Actual behaviour
N/A
